name: create manifest files

on:
  push:
    branches:
      - main  # Trigger workflow on push to the 'main' branch
  workflow_dispatch: # Allow manual trigger from GitHub Actions UI

jobs:
  update-yaml-files:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the source repository
      - name: Checkout Source Repository
        uses: actions/checkout@v3

      - name: Clone Target Repository
        run: |
          # Define the target repository and branch
          TARGET_REPO="https://argocd_access_token@github.com/anveshnani366/argocd-projects.git"
          TARGET_BRANCH="main"

          git clone --branch $TARGET_BRANCH $TARGET_REPO target-repo
